version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
  parameter-store:
    AWS_ACCESS_KEY_ID: AccessKey
    AWS_SECRET_ACCESS_KEY: SecretKey
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # start docker
      # https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html#sample-docker-custom-image-files
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - npm install
  build:
    commands:
      - npm run lint
      - npm run build
      - npm run test
      - npm run integ
      # verify the current changes do not break the example tests
      - npm link && cd examples/testing && npm link aws-embedded-metrics && npm i && npm test
